version: '3'

services:

  db:
    image: postgres
    restart: always
    container_name: myWeldingLogLocal
    volumes:
      - ./vol_folder:/var/lib/postgresql
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=mysecretpassword"
      - "POSTGRES_DB=weldingLog"
    ports:
      - 22051:5432